#
#▀██▀  ▀█▀ ▀██    ▄    ██                       ▄            ▄█▀▀▀▄█                                           ▀██▀▀█▄                    ▄                     ▄
# ██    █   ██  ▄██▄  ▄▄▄  ▄▄ ▄▄ ▄▄    ▄▄▄▄   ▄██▄    ▄▄▄▄   ██▄▄  ▀    ▄▄▄▄  ▄▄▄ ▄▄  ▄▄▄▄ ▄▄▄   ▄▄▄▄  ▄▄▄ ▄▄   ██   ██ ▄▄▄ ▄▄    ▄▄▄   ▄██▄    ▄▄▄▄    ▄▄▄▄  ▄██▄    ▄▄▄   ▄▄▄ ▄▄
# ██    █   ██   ██    ██   ██ ██ ██  ▀▀ ▄██   ██   ▄█▄▄▄██   ▀▀███▄  ▄█▄▄▄██  ██▀ ▀▀  ▀█▄  █  ▄█▄▄▄██  ██▀ ▀▀  ██▄▄▄█▀  ██▀ ▀▀ ▄█  ▀█▄  ██   ▄█▄▄▄██ ▄█   ▀▀  ██   ▄█  ▀█▄  ██▀ ▀▀
# ██    █   ██   ██    ██   ██ ██ ██  ▄█▀ ██   ██   ██      ▄     ▀██ ██       ██       ▀█▄█   ██       ██      ██       ██     ██   ██  ██   ██      ██       ██   ██   ██  ██
#  ▀█▄▄▀   ▄██▄  ▀█▄▀ ▄██▄ ▄██ ██ ██▄ ▀█▄▄▀█▀  ▀█▄▀  ▀█▄▄▄▀ █▀▄▄▄▄█▀   ▀█▄▄▄▀ ▄██▄       ▀█     ▀█▄▄▄▀ ▄██▄    ▄██▄     ▄██▄     ▀█▄▄█▀  ▀█▄▀  ▀█▄▄▄▀  ▀█▄▄▄▀  ▀█▄▀  ▀█▄▄█▀ ▄██▄
#

# Основные настройки
main-settings:
  # Префикс плагина
  prefix: "&f&l[&c&lЗащита&f&l]"
  # Включить ли команды добавления новых игроков в конфиг
  enable-admin-commands: false
  # Интервал основной проверки в тиках (не трогайте, если не знаете, как это работает)
  check-interval: 40

# Настройки файлов
file-settings:
  # Имя файла с данными игроков. (по умолчанию - data.yml)
  data-file: "data.yml"
  # Имя файла с логами. (по умолчанию - log.yml)
  log-file: "log.yml"

# Настройки дополнительных блокировок
blocking-settings:
  # Блокировать ли выбрасывание предметов
  block-item-drop: true
  # Блокировать ли подбор предметов
  block-item-pickup: true
  # Блокировать ли таб-комплит (работает против /ver + tab)
  block-tab-complete: true
  # Делать ли игрока бессмертным во время ввода пароля
  block-damage: true
  # Блокировать ли возможность наносить вред мобам и игрокам во время ввода пароля
  block-damaging-entity: true
  # Блокировать ли возможность открывать инвентари во время ввода пароля (меню и т.п.)
  block-inventory-open: false
  # Скрывать ли игрока из таб листа при вводе пароля
  hide-on-entering: true
  # Скрывать ли других игроков от человека вводящего пароль
  hide-other-on-entering: true
  # Разрешить ли двигать головой во время ввода пароля
  allow-orientation-change: false

# Настройки сессии
session-settings:
  # Сохранять ли данные об игроке чтобы ему не нужно было вводить админ пас при перезаходе
  session: true
  # Удалять ли данные об игроке через некоторое время
  session-time-enabled: false
  # Время через которое данные о зарегистрированном игроке удалятся в секундах (отсчет идет от момента ввода пароля)
  session-time: 21600 #(6 часов)

# Настройки наказаний
punish-settings:
  # Включить ли наказания за неверно введенный админ-пароль
  enable-attempts: true
  # Максимальное число попыток ввода админ-пароля
  max-attempts: 3
  # Включить ли время на ввод админ-пароля
  enable-time: true
  # Время за которое игрок будет должен ввести админ-пароль в секундах
  time: 60
  # Включить ли наказания за перезаход на сервер если игрок выходит без ввода админ-пароля
  enable-rejoin: true
  # Максимальное число перезаходов на сервер если игрок выходит без ввода верного админ-пароля
  max-rejoins: 3

# Настройки повышенной безопасности
secure-settings:
  # Применять ли наказания к операторам которых нет в списке
  enable-op-whitelist: false
  # Применять ли наказания к тем, кто не находится в конфиге, но имеет админ-права
  enable-notadmin-punish: false
  # Применять ли наказания к людям, которые имеют запрещенные права
  enable-permission-blacklist: false
  # Включить ли IPWhitelist для администраторов
  enable-ip-whitelist: false
  # Включить ли возможность использовать команду /usp только из консоли
  only-console-usp: false
  # Выключать ли сервер, если отключается плагин
  shutdown-on-disable: true
  # Выключать ли сервер только если включены плугмано-подобные плагины
  shutdown-on-disable-only-if-plugman: true
  # Разрешить ли ряду игроков входить в игру без админ пароля (отключено по умолчанию и небезопасно)
  enable-excluded-players: false
  # Вызывать ли ServerProtectorPasswordEnterEvent при вводе пароля игроком? (Отключено по умолчанию в целях безопасности)
  call-event-on-password-enter: false

# Команды, которые будут применяться к нарушителям
commands:
  # Команды, которые будут применяться к тем, у кого есть админ-права, но кого нет в конфиге
  not-in-config:
    - "kick %player% Вас нет в списке администраторов!"
    - "deop %player%"

  # Команды, которые будут применяться к тем, у кого есть админ-права, но он не прописан в вайтлисте
  not-in-opwhitelist:
    - "deop %player%"
  #- 'ban %player% Вам нельзя иметь права оператора!'

  # Команды, которые будут применяться к тем, кто имеет запрещенные права (отключено по умолчанию)
  have-blacklisted-perm:
    - "lp user %player% permission clear"
  #- 'ban %player% Вам нельзя иметь такие права!'

  # Команды, которые будут применяться к тем, кто вошел с админ-правами, указан в конфиге, но имеет не админский IP (отключено по умолчанию)
  not-admin-ip:
    - "kick %player% Ваш IP не находится в вайтлисте"
  #- 'deop %player'

  # Команды, которые будут применяться к тем, кто ввел пас неверно за отведенные ему попытки
  failed-pass:
    - "ban %player% Вы ввели админ-пароль неверно, ваш аккаунт заморожен"
    - "deop %player%"

  # Команды, которые будут применяться к тем, кто не ввел пас за отведенное время
  failed-time:
    - "kick %player% Вы не успели ввести админ-пароль за отведенный срок"
    - "deop %player%"
  # Команды, которые будут применяться к тем, кто перезашел на сервер без ввода верного пароля слишком много раз
  failed-rejoin:
    - "ban %player% Вы слишком часто перезаходили на сервер не вводя пас"
    - "deop %player%"

# Права, за которые игроку будет необходимо ввести админ-пароль (не стесняйтесь добавлять свои!)
permissions:
  - "*"
  - "bukkit.*"
  - "minecraft.*"
  - "essentials.*"
  - "cmi.*"
  - "worldguard.*"
  - "worldedit.*"
  - "fawe.*"
  - "permissions.*"
  - "luckperms.*"
  - "luckperms.editor"
  - "luckperms.applyedits"
  - "citizens.*"
  - "citizenscmd.*"
  - "znpcs.*"
  - "holograms.*"
  - "multiverse.*"
  - "coreprotect.*"
  - "mycommand.*"
  - "towny.*"
  - "matrix.*"
  - "vulcan.*"
  - "dh.admin"
  - "ls.admin"
  - "fawe.admin"
  - "authme.admin"
  - "protocol.admin"
  - "placeholderapi.admin"
  - "plugman.admin"
  - "plugman.download"
  - "serverprotector.admin"

# Права, которые никто, кроме игроков из раздела excluded-players, не сможет иметь (отключено по умолчанию.)
blacklisted-perms:
  - "*"

# Каким игрокам разрешено иметь ОП права
op-whitelist:
  - Overwrite
  - test99999

# С каких IP и каким игрокам разрешено входить с админ-правами
# Вы можете указать только часть IP адреса, чтобы разрешить вход людям с динамическим IP. К примеру 1.2.3.4 -> 1.2.3.*
ip-whitelist:
  # Игрок 1
  test99999:
    - 127.0.0.1
    - 0.0.0.0
  # Игрок 2
  test123123:
    - 228.13.37.*

# Какие игроки будут исключены из проверок (каждой проверке - свой тип)
excluded-players:
  # Игроки, которым не нужно будет вводить админ-пароль
  admin-pass:
    - test99999
    - test123123
  # Игроки, которые не будут проверяться на наличие в op-whitelist
  op-whitelist:
    - test99999
    - test123123
  # Игроки, которые не будут проверяться на наличие в ip-whitelist
  ip-whitelist:
    - test99999
    - test123123
  # Игроки, которым можно будет иметь заблокированные права
  blacklisted-perms:
    - test99999
    - test123123
