blocking-settings:
  hide-on-entering: true
  hide-other-on-entering: true

commands:
  not-in-config:
    - "kick %player% Вас нет в списке администраторов!"

  failed-pass:
    - "ban %player% Вы ввели админ-пароль неверно, ваш аккаунт заморожен"

  failed-time:
    - "kick %player% Вы не успели ввести админ-пароль за отведенный срок"

  failed-rejoin:
    - "ban %player% Вы слишком часто перезаходили на сервер не вводя пас"

permissions:
  - "*"
  - "bukkit.*"
  - "minecraft.*"
  - "essentials.*"
  - "cmi.*"
  - "worldguard.*"
  - "worldedit.*"
  - "fawe.*"
  - "permissions.*"
  - "luckperms.*"
  - "luckperms.editor"
  - "luckperms.applyedits"
  - "citizens.*"
  - "citizenscmd.*"
  - "znpcs.*"
  - "holograms.*"
  - "multiverse.*"
  - "coreprotect.*"
  - "mycommand.*"
  - "towny.*"
  - "matrix.*"
  - "vulcan.*"
  - "dh.admin"
  - "ls.admin"
  - "fawe.admin"
  - "authme.admin"
  - "protocol.admin"
  - "placeholderapi.admin"
  - "plugman.admin"
  - "plugman.download"
  - "serverprotector.admin"

excluded-players:
  - PadowYT2
