#
#▀██▀  ▀█▀ ▀██    ▄    ██                       ▄            ▄█▀▀▀▄█                                           ▀██▀▀█▄                    ▄                     ▄
# ██    █   ██  ▄██▄  ▄▄▄  ▄▄ ▄▄ ▄▄    ▄▄▄▄   ▄██▄    ▄▄▄▄   ██▄▄  ▀    ▄▄▄▄  ▄▄▄ ▄▄  ▄▄▄▄ ▄▄▄   ▄▄▄▄  ▄▄▄ ▄▄   ██   ██ ▄▄▄ ▄▄    ▄▄▄   ▄██▄    ▄▄▄▄    ▄▄▄▄  ▄██▄    ▄▄▄   ▄▄▄ ▄▄
# ██    █   ██   ██    ██   ██ ██ ██  ▀▀ ▄██   ██   ▄█▄▄▄██   ▀▀███▄  ▄█▄▄▄██  ██▀ ▀▀  ▀█▄  █  ▄█▄▄▄██  ██▀ ▀▀  ██▄▄▄█▀  ██▀ ▀▀ ▄█  ▀█▄  ██   ▄█▄▄▄██ ▄█   ▀▀  ██   ▄█  ▀█▄  ██▀ ▀▀
# ██    █   ██   ██    ██   ██ ██ ██  ▄█▀ ██   ██   ██      ▄     ▀██ ██       ██       ▀█▄█   ██       ██      ██       ██     ██   ██  ██   ██      ██       ██   ██   ██  ██
#  ▀█▄▄▀   ▄██▄  ▀█▄▀ ▄██▄ ▄██ ██ ██▄ ▀█▄▄▀█▀  ▀█▄▀  ▀█▄▄▄▀ █▀▄▄▄▄█▀   ▀█▄▄▄▀ ▄██▄       ▀█     ▀█▄▄▄▀ ▄██▄    ▄██▄     ▄██▄     ▀█▄▄█▀  ▀█▄▀  ▀█▄▄▄▀  ▀█▄▄▄▀  ▀█▄▀  ▀█▄▄█▀ ▄██▄
#

# Основные настройки
main-settings:
  # Префикс плагина
  prefix: "&f&l[&c&lЗащита&f&l]"

# Настройки дополнительных блокировок
blocking-settings:
  # Блокировать ли выбрасывание предметов
  block-item-drop: true
  # Блокировать ли подбор предметов
  block-item-pickup: true
  # Блокировать ли таб-комплит (работает против /ver + tab)
  block-tab-complete: true
  # Делать ли игрока бессмертным во время ввода пароля
  block-damage: true
  # Блокировать ли возможность наносить вред мобам и игрокам во время ввода пароля
  block-damaging-entity: true
  # Блокировать ли возможность открывать инвентари во время ввода пароля (меню и т.п.)
  block-inventory-open: false
  # Скрывать ли игрока из таб листа при вводе пароля
  hide-on-entering: true
  # Скрывать ли других игроков от человека вводящего пароль
  hide-other-on-entering: true
  # Разрешить ли двигать головой во время ввода пароля
  allow-orientation-change: false

# Команды, которые будут применяться к нарушителям
commands:
  # Команды, которые будут применяться к тем, у кого есть админ-права, но кого нет в конфиге
  not-in-config:
    - "kick %player% Вас нет в списке администраторов!"

  # Команды, которые будут применяться к тем, кто ввел пас неверно за отведенные ему попытки
  failed-pass:
    - "ban %player% Вы ввели админ-пароль неверно, ваш аккаунт заморожен"

  # Команды, которые будут применяться к тем, кто не ввел пас за отведенное время
  failed-time:
    - "kick %player% Вы не успели ввести админ-пароль за отведенный срок"

  # Команды, которые будут применяться к тем, кто перезашел на сервер без ввода верного пароля слишком много раз
  failed-rejoin:
    - "ban %player% Вы слишком часто перезаходили на сервер не вводя пас"

# Права, за которые игроку будет необходимо ввести админ-пароль (не стесняйтесь добавлять свои!)
permissions:
  - "*"
  - "bukkit.*"
  - "minecraft.*"
  - "essentials.*"
  - "cmi.*"
  - "worldguard.*"
  - "worldedit.*"
  - "fawe.*"
  - "permissions.*"
  - "luckperms.*"
  - "luckperms.editor"
  - "luckperms.applyedits"
  - "citizens.*"
  - "citizenscmd.*"
  - "znpcs.*"
  - "holograms.*"
  - "multiverse.*"
  - "coreprotect.*"
  - "mycommand.*"
  - "towny.*"
  - "matrix.*"
  - "vulcan.*"
  - "dh.admin"
  - "ls.admin"
  - "fawe.admin"
  - "authme.admin"
  - "protocol.admin"
  - "placeholderapi.admin"
  - "plugman.admin"
  - "plugman.download"
  - "serverprotector.admin"

# Какие игроки будут исключены из проверки
excluded-players:
  - test99999
  - test123123
