name: "UltimateServerProtector"
version: "31.0"
author: OverwriteMC
main: ru.overwrite.protect.ServerProtector
api-version: 1.13
folia-supported: true
load-priority: STARTUP
loadafter: [LuckPerms, BungeeGuard]
commands:
  ultimateserverprotector:
    aliases: [usp, serverprotector]
permissions:
  serverprotector.admin:
    children:
      serverprotector.reload: true
      serverprotector.reboot: true
      serverprotector.setpass: true
      serverprotector.addop: true
      serverprotector.addip: true
      serverprotector.rempass: true
      serverprotector.remop: true
      serverprotector.remip: true
