name: "UltimateServerProtector"
version: "31.0"
author: OverwriteMC
main: ru.overwrite.protect.ServerProtector
api-version: 1.13
load-priority: STARTUP
loadafter: [LuckPerms]
commands:
  ultimateserverprotector:
    aliases: [usp, serverprotector]
permissions:
  serverprotector.admin:
    children:
      serverprotector.reload: true
      serverprotector.setpass: true
      serverprotector.rempass: true
